version: '3.8'

services:
  app:
    container_name: microsservice_estabelecimentos
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend_network
    ports:
      - '4321:4321'
    env_file:
      - .env
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    command: >
      sh -c "echo 'Aguardando MySQL...' && \
      until mysql -h mysql_estabelecimentos -u root -p${DATABASE_PASSWORD} -e 'select 1'; do \
        echo 'Aguardando MySQL...'; \
        sleep 5; \
      done && \
      npm run prisma:migrate:deploy && npm run prisma:generate && npm run start:production"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql_estabelecimentos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - '3307:3306'
    volumes:
      - mysql_ms_estabelecimento:/var/lib/mysql
    networks:
      - backend_network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  backend_network:
    external: true

volumes:
  mysql_ms_estabelecimento:
    driver: local
