name: Secure Deploy with Docker Compose

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup SSH access to the VPS
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. Add GitHub and VPS to known_hosts
      - name: Add known_hosts
        run: |
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          ssh-keyscan -H 177.153.51.58 >> ~/.ssh/known_hosts

      # 4. Deploy with Docker Compose
      - name: Deploy with Docker Compose
        run: |
          ssh root@177.153.51.58 << 'EOF'
          set -e

          REPO_PATH="/home/grocha/applications/ms_estabelecimentos"

          if [ ! -d "$REPO_PATH" ]; then
            echo "Clonando o repositório..."
            git clone git@github.com:dryingcore/ms_estabelecimentos.git "$REPO_PATH"
          else
            echo "Atualizando o repositório existente..."
            cd "$REPO_PATH"
            git reset --hard
            git pull origin main
          fi

          cd "$REPO_PATH"
          docker-compose build
          docker-compose down
          docker-compose up -d
          EOF
